using Aula_003;
Console.Clear();
Exercicio1.Executar();
await Task.Delay(TimeSpan.FromSeconds(3));
Console.Clear();
Exercicio2.Executar();
await Task.Delay(TimeSpan.FromSeconds(3));
Console.Clear();
Exercicio3.Executar();
await Task.Delay(TimeSpan.FromSeconds(3));
Console.Clear();
Exercicio4.Executar();
await Task.Delay(TimeSpan.FromSeconds(3));
Console.Clear();
Exercicio5.Executar();
await Task.Delay(TimeSpan.FromSeconds(3));
Console.Clear();